home/urls.py
from django.conf.urls import url
from . import views
app_name='home'

urlpatterns = [
url(r'^$', views.Home.as_view(), name = 'home'),
url(r'^crops/', views.check_crops, name = 'crops'),
url(r'^resp/', views.get_details, name = 'resp'),
url(r'^details/', views.all_details, name = 'det'),
url(r'^pest/', views.pests_predictor, name = 'pest'),
url(r'^imagesubmit/', views.image_submit, name = 'pest'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import home.views as views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^$', RedirectView.as_view(url='/home/')),
]

home/models.py
from django.db import models
#rom django.contrib.gis.geos import Point
#from location_field.models.spatial import LocationField
from django.utils.translation import gettext as _
import datetime

class cropModel(models.Model):
    crop = models.CharField(max_length=200)
    devId = models.IntegerField()
    date = models.DateField(_("Date"), default=datetime.date.today)
    #city = models.CharField(max_length=255)
    #location = LocationField(based_fields=['city'], zoom=7, default=Point(1.0, 1.0))
    #objects = models.GeoManager()

home/forms.py
from django import forms
from .models import *

class cropsForm(forms.ModelForm):

    class Meta:
        model = cropModel
        fields = ('crop', 'devId','date')

home/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.views.generic import TemplateView
import random
import paho.mqtt.client as mqtt
from django.views.decorators.csrf import csrf_exempt, csrf_protect
import json
from django.http import JsonResponse
from watson_developer_cloud import VisualRecognitionV3

class Home(TemplateView):
    template_name = 'home.html'

def on_connect(client, userdata, flags, rc):
    print(str(rc))
    mqttc.subscribe("/temp",qos=0)
    print("sub")

def on_message(client, obj, msg):
    print(msg.topic + " " + str(msg.qos) + " " + str(msg.payload))


def check_crops(request):
    mqttc=mqtt.Client()
    mqttc.on_message=on_message
    #mqttc.max_queued_messages_set(self, 10)
    mqttc.username_pw_set("dfxukbgb", "lq_IHyYetOBV")
    mqttc.connect("m20.cloudmqtt.com", 14917)
    mqttc.on_connect=on_connect

    form = cropsForm()
    if request.method == 'POST': # If the form has been submitted...
        form = cropsForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass

            result = request.POST
            mqttc.publish("crop",result["crop"])
            mqttc.publish("devId",result["devId"])
            mqttc.publish("date",result["date"])
    return render(request, 'symptoms.html', {'form': form,'type':"Heart"})

@csrf_exempt
def get_details(request):
    data = json.loads(request.body)
    print("hekklo",data)
    return JsonResponse({'status':'200'})

def all_details(request):
    return render(request,'success.html',{'ideal': '0.0956654457', 'temp': '0', 'curr_date_water': '162.0', 'humidity': '0', 'actual': '0', 'curr_date': '3', 'total_water_vol': '486.0'})


def pests_predictor(request):
    return render(request,'pests.html')

def image_submit(request):
    visual_recognition = VisualRecognitionV3('2016-05-20', api_key='8c3cf9aeb2d85c594739a9a90c0ff684a5e6aaa7')
    print(json.dumps(visual_recognition.classify(images_url="https://transfer.sh/b2BIm/garden.jpg"), indent=2))
    return render(request,'home.html')

home/templates/base.html
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Crop health{% endblock %}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel = 'stylesheet' href="{% static 'home/base.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
</head>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	</script>

  </head>
  <body  {% block body_style %} {% endblock %}>
<nav class="navbar navbar-inverse" style="margin-bottom:0;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home:home' %}">Agrocot</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li {% block nav_home %}class="active"{% endblock %}><a href="{% url 'home:pest' %}">Pest Predictor</a></li>
      <li {% block nav_crops %}{% endblock %}><a href="{% url 'home:crops' %}">Irrigation level</a></li>
    </ul>
  </div>
</nav>
<div id = "content">
{% block content %}{% endblock %}
</div>
<footer class='footer'>
<br>
  <p align="justify"><font size="2px" color="grey"><center>Copyright 2017 &copy; <br></center></font></p>    
</footer>
  </body>

</html>

home/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Agrotech{% endblock %}
{% block body_style %}style="background-image: url({% static 'background.jpg' %});background-size:cover;"
{% endblock %}
<style>
html,
body,
.container {
  height: 100%;
  width: 100%;
}
.container {
  display: flex;
  align-items: center;
  justify-content: center;
}
.mydiv {
  width: 80px;
}
</style>
{% block content %}
<div class="container">
  <div class="mydiv" style="margin-top:5cm;"><center><font size="8"><strong>Agrocot</strong></center></font></div>
</div>
{% endblock %}

home/templates/pests.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Agrotech{% endblock %}
{% block body_style %}style="background-image: url({% static 'background.jpg' %});background-size:cover;"
{% endblock %}
<style>
html,
body,
.container {
  height: 100%;
  width: 100%;
}
.container {
  display: flex;
  align-items: center;
  justify-content: center;
}
.mydiv {
  width: 80px;
}
</style>
{% block content %}
 <form action="/home/imagesubmit">
   <h1>Crop image:</h1> <input type="file" name="file" />
  <input type="image" src="submit.gif" alt="Submit">
</form>
{% endblock %}

home/templates/success.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Agrotech{% endblock %}
{% block body_style %}style="background-image: url({% static 'background.jpg' %});background-size:cover;"
{% endblock %}
<style>
html,
body,
.container {
  height: 100%;
  width: 100%;
}
.container {
  display: flex;
  align-items: center;
  justify-content: center;
}
.mydiv {
  width: 80px;
}
</style>
{% block content %}
<center>
  <div>
<h1>NDVI Ideal: {{ideal}}</h1> 
<h1>NDVI Actual: {{actual}}</h1> 
<h1>Temperature: {{temp}}</h1> 
<h1>Total water volume: {{total_water_vol}}</h1> 
<h1>Humidity: {{humidity}}</h1> 
  </div>
</center>
<div class="container">
  <div class="mydiv" style="margin-top:5cm;"><center><font size="8"><strong>You have {{type}} disease.</strong></center></font></div>
</div>
{% endblock %}

home/templates/symptoms.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Irrigation amount{% endblock %}
{% block content %}
<h1><center>Irrigation amount at your door</center></h1>
<form class="large" method="post" action="home/crops/">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
  </div>
  {% endfor %}
  <center> <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Submit</button>
    </div></center>
</form>
<center>
<a href="/home/details">
      <button type="submit" class="btn btn-primary" >View Details</button>
</a>
</center>
{% endblock %}